version: '3'
services:
  mongo:
    container_name: 'mongoDb'
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: salt_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - network

  salt-master:
    container_name: salt-master
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4505:4505"
      - "4506:4506"
      - "8080:8080"
    volumes:
      - ./srv:/srv
      - logs:/var/log/salt
      - salt-key:/etc/salt/pki
      - salt-cache:/var/cache/salt/master
      - salt-pid:/var/run/salt-master.pid
    networks:
      - network
    depends_on:
      - mongo

volumes:
  mongodb:
  salt-key:
  salt-pid:
  salt-cache:
  logs:
networks:
  network:
    driver: bridge