version: '3.8'

services:
  mongo:
    container_name: 'mongoDb'
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: salt_db
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db
    networks:
      - network

  salt-master:
    container_name: salt-master
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4505:4505"
      - "4506:4506"
      - "8080:8080"
    volumes:
      - ./srv:/srv
      - ./master:/etc/salt/master.d
      - ./volumes/salt/log:/var/log/salt
      - ./volumes/salt/pki:/etc/salt/pki
      - ./volumes/salt/cache:/var/cache/salt/master
      - ./volumes/salt/pid:/var/run/salt-master.pid
    networks:
      - network
    depends_on:
      - mongo

networks:
  network:
    driver: bridge